name: Test ArcanBetFeed Orchestrator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-orchestrator:
    runs-on: ubuntu-latest

    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      ARCAN_SHADOW_TRACKER_ENDPOINT: ${{ secrets.ARCAN_SHADOW_TRACKER_ENDPOINT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run orchestrator test
      run: python tests/test_orchestrator.py
